releasetools.py: Cleanup and add incremental support
* Removed unused TrustZone asserts
* Fixes error: AttributeError: 'DeviceSpecificParams' object has no attribute 'input_zip'